version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: my_mysql_teste
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123!
      MYSQL_DATABASE: testeDev
      MYSQL_USER: dev
      MYSQL_PASSWORD: senha@123!
    ports:
      - "8383:3306"
    volumes:
      - ./data-v8-teste-dev:/var/lib/mysql

  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin:latest
  #  container_name: my_phpmyadmin
  #  restart: always
  #  environment:
  #    PMA_HOST: mysql
  #    MYSQL_ROOT_PASSWORD: lvl@2784!
  #  ports:
  #    - "8080:80"
  #  depends_on:
  #    - mysql