version: '3.8'

services:
  mysql:
    image: mysql:8.0.36
    container_name: my_mysql_teste
    env_file: ./env/mysql.env
    ports:
      - "8383:3306"
    volumes:
      - ./data-v8-teste-dev:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10
  
  api-1: &api
    image: francilioalencar/teste-tecnico-dev:v1.0
    env_file: ./env/app.env
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
  api-2:
    <<: *api

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - api-1
      - api-2

volumes:
  mysql-data: